### ISSUE TITLE
Observe value are too small then the server says not found by 404 HTTP Code

### ISSUE THREAD

**Issue by milanowicz** [jtl-software/goprometrics#11]
I discovered that the lowest value may be 0.0001 and this is still accepted by the server, below this value the message comes:

``PUT http://127.0.0.1:9111/observe/NAMESPACE/NAME/0.000001` resulted in a `404 Not Found` response: 404 page not found`

**Comment by sleipi** [comment]
@Milanowicz 

Unfortunately, I can not reproduce the reported behavior. Could you please send me the output from 
```
curl 127.0.0.1:9112/metrics
```
after the 404 occur?

I only need the output for the particular metric NAMESPACE_NAME

**Comment by milanowicz** [comment]
@sleipi I check this, perhaps it's gone, hopefully

**Comment by milanowicz** [comment]
@sleipi look in here

- https://github.com/jtl-software/goprometrics/pull/15
- https://github.com/jtl-software/goprometrics-client/commits/404_on_observe
